# Arraylere Manuel Tip Verme

**istersem elimdeki listenin elemanlarinin icinde floatlar varsa onlarin kusuratlarini yollayip sadece intlerden olusmasini isteyebilirim veya string olarak tutmak isteyebilirim. bu durumda kendim manuel olarak tip belirtmem gerekir**

**onemli bir not, eger string halinde int'e ya da float'a donusebilecek bir deger varsa onlar sayi olarak cast edilebilir**

**ama suna dikkat etmem lazim, string halden floata ya da inte direkt cast edeceksem buna uygun formatta sayilar olmali, string bir int float karisik diziyi floata cast edebilirim ama float string'i inte cast edemem** 

In [5]:
import numpy as np

In [6]:
x = np.array([1, 2.7, 6, 9, "5", "5.80"], dtype="float")

In [19]:
x

array([1, 2, 6, 9, 5])

In [21]:
x = np.array([1, 2.7, 6, 9, "5"], int)

In [22]:
x

array([1, 2, 6, 9, 5])

In [23]:
x = np.array([1, 2.7, 6, 9, "5"], dtype="float")

In [24]:
x

array([1. , 2.7, 6. , 9. , 5. ])

In [25]:
x = x = np.array([1, 2.7, 6, 9, "5", "5.90"], float)

In [26]:
x

array([1. , 2.7, 6. , 9. , 5. , 5.9])

In [27]:
z = np.array([1, 2, 6, 9, "5"], dtype = "int")

In [22]:
z

array([1, 2, 6, 9, 5])

In [28]:
k = np.array([1, 2.7, 6, 9, "5", "5.90"], str)

In [29]:
k

array(['1', '2.7', '6', '9', '5', '5.90'], dtype='<U4')