# Zero Array

**zero array deyince aklina booleanlar ve stringlerin de zero halleri de gelsin, stringlerde bosluk, booleanlarda false olacak**

**default yaratilma degeri float sifirdir**

**zeros((shape), dtype) --> eger bu sirada kullanmazsam hata alirim** 

**shape'i illa tuple olarak yazmak zorunda degilim koseli parantez olarak da shape yazabilirim**

**np.zeros([3, 8, 8]) yazdigimda elimde 3 tane 8X8'lik bi fotograf var gibi dusunebilirim, ilk sayi resim sayisini tutuyor**

**m[2,3,2] = 99 uc boyutlu arrayimde boyle bir degisiklik yaptigimda ben int ile update etmis olsamda yaratilmis halihazirdaki array'e uyacak ve float olarak onu arraya ekleyecek**

In [2]:
import numpy as np

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros(10, int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.zeros(10, str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [6]:
np.zeros((5,2), bool)

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [7]:
np.zeros(3, bool)

array([False, False, False])

In [8]:
m = np.zeros([3, 6, 6])

In [8]:
m

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [9]:
m[2,3,2] = 99

In [10]:
m

array([[[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0., 99.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]]])