# Belirtilen Elemanla Dolu Bir Array Yaratmak

**np.full((shape), neyle doldurucam, dtype)**

**shape illa tuple ile belirtilmek zorunda degil koseli parantez de olur ayrica np.full(sayi, neyle doldurucam, dtype) yazarsam bir sayi obegi verir yani row column mantiginda olmayan bir yapi donderir**

**a.shape diyerek a ndarray'inin shape'ine bakabilirim**

In [2]:
import numpy as np

In [2]:
np.full((5,5), 5, int)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [3]:
np.full((5,5), 5, float)

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [4]:
a = np.full(5, 20)

In [5]:
a

array([20, 20, 20, 20, 20])

In [6]:
type(a)

numpy.ndarray

In [9]:
a.shape

(5,)

**burda ufak bi tuhaflik var, ama kucuk bi detay, float olarak cast etmiyor, kusurati atip string yapiyor**

In [10]:
np.full((4, 5), 5.2, dtype="str")

array([['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5']], dtype='<U1')

In [11]:
np.full((4, 5), "5.2")

array([['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2']], dtype='<U3')

In [12]:
np.full((4, 5), 5.2)

array([[5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2]])

In [5]:
np.full([5,5], 2.90)

array([[2.9, 2.9, 2.9, 2.9, 2.9],
       [2.9, 2.9, 2.9, 2.9, 2.9],
       [2.9, 2.9, 2.9, 2.9, 2.9],
       [2.9, 2.9, 2.9, 2.9, 2.9],
       [2.9, 2.9, 2.9, 2.9, 2.9]])