# Ardisik Sayilardan Array Arange Etmek

**python range'e cok benziyor, start,stop,step mantigi ayni**

**burda su onemli, np.arange(12, 3, -2) dedigimde dahil olmayan yine stop, buyuk olan dahil edilmez gibi dusunme, dahil edilmeyen stop**

**start degeri vermezsem default olarak 0 aliyor**

In [1]:
import numpy as np

In [3]:
np.arange(1, 21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [2]:
a = np.arange(3, 12, 5)

In [3]:
type(a)

numpy.ndarray

In [4]:
np.arange(45, 10, -5)

array([45, 40, 35, 30, 25, 20, 15])

In [5]:
b = np.arange(5, 101, 5)

In [6]:
b

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [7]:
type(b)

numpy.ndarray

In [11]:
np.arange(100, 0, -5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15,  10,   5])