# Ardisik Sayilardan Array Arange Etmek

**python range'e cok benziyor, start,stop,step mantigi ayni**

**burda su onemli, np.arange(12, 3, -2) dedigimde dahil olmayan yine stop, buyuk olan dahil edilmez gibi dusunme, dahil edilmeyen stop**

**start degeri vermezsem default olarak 0 aliyor**

**buyukten kucuge gidebilmesi icin step degeri olarak -1 vermem gerekir, step degeri vermezsem calismaz, bana bos bir ndarray dondurur**

In [1]:
import numpy as np

In [10]:
a = np.arange(1, -2, -1)

In [11]:
a

array([ 1,  0, -1])

In [4]:
a = np.arange(3, 12, 5)

In [3]:
type(a)

numpy.ndarray

In [4]:
np.arange(45, 10, -5)

array([45, 40, 35, 30, 25, 20, 15])

In [14]:
b = np.arange(5, 101, 5)

In [15]:
b

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [16]:
type(b)

numpy.ndarray

In [17]:
np.arange(100, 0, -5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15,  10,   5])

In [19]:
b.shape

(20,)