# Iki sayiyi belli sayida esit araliklara bolme

**linspace'i zihninde sihirli bir degnek olarak canlandir ve uclari dahil olacak sekilde esit araliklara boldugunu hayal et**

**tamam bunu hayal et ama ozunde yaptigi sey, totalde, verdigim sayida sayi dondurmesi ayni zamanda**

**girdigim sayilar da dahil olmak uzere toplamda elimde kac sayi olacagini bana veriyor, girdigim bu uc noktalar float da olabilir int de olabilir fark etmez**

**aralik sayisi yazmazsam default olarak 50 esit parcaya ayirir**

**eger istersem endpoint dahil olmasin diyebilirim**

**python'da fonksiyonlar sira gozettigi icin parametrede num olarak belirtmeme gerek yoktu belirtsem de belirtmesem de ayni sekilde calisacak**
 
 **istersem ayirdigim parcalarin tamamini int yapabilirim**
 
 **np.linspace(start, stop, num=4, dtype = int)**
 
 **istersem buyukten kucuge de gidebilirim**


In [1]:
import numpy as np


In [2]:
np.linspace(1, 2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [3]:
np.linspace(1, 2, 5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [4]:
np.linspace(1, 2, num = 5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [3]:
np.linspace(1, 10, num = 5, endpoint=False)

array([1. , 2.8, 4.6, 6.4, 8.2])

In [6]:
np.linspace(1, 10, num = 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [11]:
np.linspace(1, 100, num=4, dtype = int)

array([  1,  34,  67, 100])

In [4]:
np.linspace(1, 10, num = 5, endpoint=False, dtype = int)

array([1, 2, 4, 6, 8])

In [5]:
np.linspace(100, 10, num = 5, endpoint=False, dtype = int)

array([100,  82,  64,  46,  28])