# Random Integerlarla Array Olusturmak

**dikkat et azonce np.random.normal'di simdi np.random.randint kullanicam**

**burda randomluk uniform yani her bir sayi esit olasiliklarla gelecek**

**np.random.randint([low, high),(size))**

**eger size belirtmezsem yalnizca bir tane sayi uretiyor, size belirttigim an ndarray olusuyor**

**eger tek bir deger girersem default olarak baslangici sifir olan bitisi verdigim sayi olan ama dahil olmayan bir random sayi olusuyor**

**Return random integers from `low` (inclusive) to `high` (exclusive).

 If `high` is None (the default), then results are from [0, `low`).

In [3]:
import numpy as np

In [5]:
ece = np.random.randint(3, 50)

In [6]:
ece

22

In [4]:
a = np.random.randint(low = 1,high= 20, size = (4, 5))

In [5]:
a

array([[14,  6, 11, 12, 16],
       [14, 19, 17,  9,  8],
       [13, 14,  8,  8, 15],
       [17, 12,  1, 15, 17]])

In [6]:
b = np.random.randint(1, 20, (5, ))

In [7]:
b

array([13,  8, 12,  5, 10])

In [10]:
type(b)

numpy.ndarray

In [11]:
b.shape

(5,)

In [12]:
b.ndim

1

In [18]:
c = np.random.randint(low = 1, high= 30)

In [19]:
c

27

In [15]:
type(c)

int

In [9]:
d = np.random.randint(low = 40, size = (4, 5))

In [10]:
d

array([[38, 36, 15, 23, 20],
       [20, 19, 23, 30, 39],
       [27, 39, 38, 13, 10],
       [12, 23, 22, 35, 12]])

# Gercekten Uniform Distributiondan Mi Cekmis Bi Bakalim

In [25]:
d = {}

for _ in range(20000):
    val = np.random.randint(1, 11)
    if val not in d:
        d[val] = 1
    else:
        d[val] += 1

In [26]:
d

{5: 2075,
 10: 1975,
 8: 2045,
 1: 2026,
 2: 2042,
 3: 1984,
 4: 2023,
 7: 1919,
 6: 2033,
 9: 1878}

In [11]:
out_arr = np.random.randint(low = 0, high = 3, size = 5)
print ("Output 1D Array filled with random integers : ", out_arr)

Output 1D Array filled with random integers :  [0 0 0 2 1]


In [12]:
type(out_arr)

numpy.ndarray

In [13]:
out_arr = np.random.randint(low = 0, high = 3)

In [14]:
type(out_arr)

int