# Eyedentity Matrix

**satir sayisindan daha fazla sutun sayisi verirsem kendini ona gore ayarlayip yine de olabildigi kadar identity matrix yaratiyor**

**default sifirlari float oluyor**

In [1]:
import numpy as np

In [2]:
np.eye(N=5, M=6, dtype='int')

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

In [3]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [11]:
np.eye(5, 6, 0, int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])