# Numpy Array'i Operationlari

**python listleri arasinda * operatoru tanimli degildir iki python listini carpmaya calisirsam hata alirim**

**python listlerinde + operatoru tanimlidir ve iki listeyi concatenate edebilirim, ayrica * ile bir scaler ile carpip yine concatenate ederim**

**ama numpy listlerinde durum farkli, iki numpy arrayini carparsam ve toplarsam elementwise olarak toplar ve yeni bir ndarray olarak tutar**

**bunu yapabilmesi icin eleman sayilari ayni olmak zorunda**

**sadece iki numpy ndarrayini degil ayni zamanda bir numpy arrayi ile bir scalari da carpabilirim yine elementwise olarak tum elemanlar 3'le carpilmis olur, ama bu degisim kalici olmaz, carpilmis haline ihtiyacim olursa bir degiskene atarim, eger kalici olmasini istersem kendisini 3'le carptigim haline esitlerim**

In [1]:
import numpy as np

In [2]:
a = np.arange(1, 21)

In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(20,)

In [5]:
a.ndim

1

In [6]:
list1 = [1, 2, 3, 4, "ece", "7.90", 4]
list2 = [4, 90, "sevin"]

In [7]:
list3 = list1 + list2

In [8]:
list3


[1, 2, 3, 4, 'ece', '7.90', 4, 4, 90, 'sevin']

In [11]:
list4 = list3 * 2

In [12]:
list4

[1,
 2,
 3,
 4,
 'ece',
 '7.90',
 4,
 4,
 90,
 'sevin',
 1,
 2,
 3,
 4,
 'ece',
 '7.90',
 4,
 4,
 90,
 'sevin']

In [13]:
m = np.array([1, 2, 3])
n = np.array([4, 5, 6])
m * n 

array([ 4, 10, 18])

In [14]:
n = np.array([4, 5, 6, 7])

In [15]:
m * n 

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [17]:
try: 
    m * n 
except ValueError:
    print("olmadi")
    pass

olmadi


In [18]:
m * 3

array([3, 6, 9])

In [19]:
m

array([1, 2, 3])

In [20]:
o = m * 3

In [21]:
o

array([3, 6, 9])

In [22]:
o = o * 3

In [23]:
0

0

In [24]:
o

array([ 9, 18, 27])

In [25]:
matrix = np.arange(1, 21).reshape(4, 5)

In [26]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [27]:
matrix * 3

array([[ 3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30],
       [33, 36, 39, 42, 45],
       [48, 51, 54, 57, 60]])

In [28]:
matrix + matrix

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])