# Reshaping

**eleman sayim yani size'im ayni kalacak sekilde ndarrayimi istedigim sekle sokabilirim, eger size'lar uyusmazsa hata alirim**

**yaptigim bu islem ndarrayimi guncellemiyor**

**istersem bir dimensiondaki shape'i yazip digerini sen kendin hesapla beni yorma diyebilirim bunu da -1 vererek yaparim, ama birden fazla yeri sen hesapla diyemem dersem ValueError: can only specify one unknown dimension hatasini alirim, cokca gorursunuz bunu dedi**

**np.newaxis, : diye bir yapi kullandik ama okuyorum ve geciyorum simdilik burayi, cok mantigini anlamadim**

**None ile np.newaxis ayni seyleri yapiyor, yazildigi yere bir tane boyut ekliyor gibi dusun, bunlari 1 boyuttan iki boyuta gecerken yapti, ogrenmis oldum okey, bunu reshape ile de yapabilirdim zaten**

In [1]:
import numpy as np

In [2]:
x = np.arange(1, 21).reshape(4,5)

In [3]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
x.reshape(10, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [6]:
x.reshape(2, 2, 5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [7]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
y = x.reshape(2, 2, 5)

In [9]:
y

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [10]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [17]:
z = x.reshape(-1, -1, 5)

ValueError: can only specify one unknown dimension

In [16]:
z

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

# Boyut Eklemek

In [18]:
m = np.arange(1, 21)

In [19]:
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
m.shape

(20,)

In [22]:
m.ndim

1

In [25]:
n = m[np.newaxis, :]

In [24]:
m.shape

(20,)

In [26]:
n.shape

(1, 20)

In [27]:
n.ndim

2

In [28]:
n

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]])

In [29]:
k = n[np.newaxis, :]

In [30]:
k

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20]]])

In [31]:
k.shape

(1, 1, 20)

In [32]:
m[None, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]])

In [33]:
m[:, None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

In [34]:
a = np.arange(1, 11)

In [35]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
a.shape

(10,)

In [38]:
b = a[None, :]

In [39]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [40]:
b.shape

(1, 10)

In [41]:
c = a[:, None]

In [42]:
c

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [43]:
c.shape

(10, 1)