# Concatenation

**np.concatenate([a, b]) methodunun icine illa da numpy ndarray koymak zorunda degilim istersem python list de, tuple da koyabilirim, bu arada dikkat birlesecek olan degerleri koseli parantez icine atip birlestiriyorum**

**cok ilginc, t = (55) dersem t int olarak donuyor vay canina, ve int oldugu icin de concatenate methodu icine eklemek icin koyamiyorum**

**burda np.array([bisilerbisiler]) diye ndarray yaratirken gecerli olan mantik aynen gecerli concatenate ederken kullandigim liste eger karma bir list veya tuple'sa yine en genel hale gore cast edip oyle concatenate ediyor**

**array([1, 2, 3, 4]) cikti olarak bunu gordugunde aman 1 rowlu 4 columnlu bir sey var diye dusunme, burda row column mantigi yok, bu bir sayi obegi ve tek boyutlu yani satiri sutunu yok, row column mantigina gecebilmek icin en az 2 boyutlu olmasi gerek**

**concatenate methoduna sokabilmem icin shape'ler uyusuyor olmali**

**1 boyutluyken normal linear olarak yanina yanina ekliyor, ama isin icine satir ve sutun mantigi girmeye basladiktan sonra artik axis de devreye giriyor, yani ben bu concatenate isini istersem yukardan asagi istersem soldan saga dogru yapabilirim bunun icin de axisleri kullanirim**

**eger axis olarak hicbir sey yazmasam default olarak axis = 0 dogrultusunda yani yukardan asagi concatenate ediyor, eger axis = 1 dersem soldan saga concatenate ediyor** 

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2,3, 4])
b = np.array([10, 20, 30, 40 ,50])

In [3]:
np.concatenate([a, b])

array([ 1,  2,  3,  4, 10, 20, 30, 40, 50])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
l = [44, 55, 66, "11", 11.9]

In [6]:
np.concatenate([a, l, b])

array(['1', '2', '3', '4', '44', '55', '66', '11', '11.9', '10', '20',
       '30', '40', '50'], dtype='<U32')

In [7]:
t = (555,999)

In [14]:
type(t)

tuple

In [15]:
np.concatenate([t, a, l, b])

array([555, 999,   1,   2,   3,   4,  44,  55,  66,  10,  20,  30,  40,
        50])

In [20]:
a 

array([1, 2, 3, 4])

In [21]:
x = np.arange(1, 21).reshape(4, 5)

In [23]:
np.concatenate([x, x])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [24]:
np.concatenate([x, x], axis = 1)

array([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 16, 17, 18, 19, 20]])