# Stack

**Concatenate ile boyutlar ayni kalacak sekilde bir birlestirme yapiyordum, ama stack ile boyutu arttirarak bir birlstirme soz konusu, aradaki fark bu** 

**kullanim sekli concatenate ile ayni yine birlestirecegim degerleri koseli parantezler icinde birlestiriyorum**

**simdilik tek boyutu ogrenmem kafi, 3.boyuta gecmiyorum**

**axis=1 oldugunda soldan saga, axis = 0 oldugunda yukaridan asagiya bir ekleme yaptigini bilmem yeterli**


In [12]:
import numpy as np

In [13]:
a = np.arange(1, 6)

In [14]:
b = np.arange(6, 11)

In [15]:
c = np.arange(11, 16)

In [16]:
c

array([11, 12, 13, 14, 15])

In [17]:
a.shape

(5,)

In [18]:
b.shape

(5,)

In [19]:
c

array([11, 12, 13, 14, 15])

In [20]:
d = np.stack([a, b, c], axis = 0)

In [21]:
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [22]:
d.shape

(3, 5)