# Splitting

**python listlerinde de calisir once bunu soyleyeyim bastan, elime bir kalem aliyorum ve buraya bir centik suraya bir centik yapip o listi ya da ndarrayi parcalamis oluyorum**

**np.split(l, [2, 6]) dedigimde ilk degisken parcalayacagim sey, ikincisi de attigim centiklerin indexleri**

**kac centik varsa bir fazlasi kadar parca olusuyor**

**ve ben coklu atama yaparak bu parcalari degiskenlere atayabilirim**

**split methodu icine list de atmis olsam output olarak ndarray'lerden olusan bir list aliyorum**

In [3]:
import numpy as np

In [4]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

In [5]:
np.split(l, [2, 6])

[array([1, 2]),
 array([3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])]

In [6]:
a, b, c = np.split(l, [2, 6])

In [7]:
a

array([1, 2])

In [8]:
type(a)

numpy.ndarray

In [9]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

In [11]:
k, l, m = np.split(x, [2, 6])

In [12]:
k

array([1, 2])

In [13]:
l

array([3, 4, 5, 6])

In [14]:
m

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [15]:
ece = np.split(x, [2, 6])

In [16]:
ece


[array([1, 2]),
 array([3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])]

In [17]:
type(ece)

list

In [18]:
ece[0]

array([1, 2])

In [19]:
type(ece[0])

numpy.ndarray

In [20]:
a, b, c, d = [1, 2, 3, 4]

In [21]:
a

1