**np.sort(a) bunu yaptigimda numpy arrayi guncellenmiyor**

**a.sort() dedigimde guncelleniyor**

**np.argsort() diye cilgin bir sey var, bu method list'i siraliyor ama siralanmis elemanlarin indexlerini donduruyor, harika bisey mi cok gereksiz bisey mi henuz emin degilim**

In [1]:
import numpy as np

In [2]:
a = np.array([20, 32, 5, 30, 10])

In [3]:
a

array([20, 32,  5, 30, 10])

In [4]:
np.sort(a)

array([ 5, 10, 20, 30, 32])

In [5]:
a

array([20, 32,  5, 30, 10])

In [7]:
b = np.array([3, 5, 2, 6, 1, 4])

In [8]:
b

array([3, 5, 2, 6, 1, 4])

In [9]:
np.argsort(b)

array([4, 2, 0, 5, 1, 3], dtype=int64)