**indexleme demek elemanlara ulasmak demek, bir matrixte bir satirin tamamina ulasabilecegim gibi specific olarak bir elemanin kendisine de ulasabilirim**

**ulasabilecegim gibi ulastigim sekilde atama yaparak o elemani degistire de bilirim**

**bu guncellemeyi yaparken elimde halihazirda olusturulmus bir array oldugu icin arrayin dtyp'i neyse ona cast edilerek guncelleme yapilir**

**yorum satirlarini okumayi unutma**

**index ile slice mantigi ayni olan islemler, index ile tek bir elemana slice ile birden fazla elemana erisiyorum**

In [1]:
import numpy as np

In [5]:
a = np.arange(1, 41).reshape(8, 5)

In [6]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [7]:
a[0]

array([1, 2, 3, 4, 5])

In [7]:
a[2]

array([11, 12, 13, 14, 15])

In [8]:
b = a[0][2] #alt satirdakiyle bu satir ayni sey

In [9]:
b

3

In [10]:
type(b)

numpy.int32

In [11]:
c = a[0]

In [12]:
c

array([1, 2, 3, 4, 5])

In [13]:
type(c)

numpy.ndarray

In [14]:
c.shape

(5,)

In [18]:
d = np.arange(1, 6).reshape(5, 1)

In [19]:
d

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [20]:
d

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [10]:
a[0, 2] = "30" #bunu yapabilirim cunku sayisal bir string

In [12]:
a[0, 2] = "30.60" #bunu yapamam cunku floati int olarak guncelleyemem

ValueError: invalid literal for int() with base 10: '30.60'

# Slicing

**su satirdan bu satira kadar tum satirlari al dersem yapiyi koruyarak dondurur**

In [21]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [13]:
a[0:3]

array([[ 1,  2, 30,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
a[:2]

array([[ 1,  2, 30,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
a[0:]

array([[ 1,  2, 30,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [16]:
a[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [17]:
a[::2]

array([[ 1,  2, 30,  4,  5],
       [11, 12, 13, 14, 15]])

In [18]:
a[1::2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [19]:
a[2,3]

14

In [23]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [22]:
a[:, 3] #tum rowlari al ama sutun olarak 3.sutunu al, yani 3.col'u al ve butun satirlarla kesistir

array([ 4,  9, 14, 19, 24, 29, 34, 39])

**ve bunu bana bir sayi obegi olarak dondurecek**

In [22]:
a[:, 3].shape

(4,)

**sol taraf satir, sag taraf sutun**

In [24]:
m = a[::2,3]

In [25]:
m

array([ 4, 14, 24, 34])

In [26]:
m.shape

(4,)

In [27]:
m.size

4

In [25]:
a[0, :] #ilk rowu al ve tum sutunlarla kesistir

array([ 1,  2, 30,  4,  5])

In [26]:
a[0] #aynisini bununla da yapabilirdim

array([ 1,  2, 30,  4,  5])

In [28]:
a[0, 2:4] #ayni slice mantigini sutunlar icin de yapabilirim

array([30,  4])

In [4]:
b = np.arange(1, 41).reshape(8, 5)

In [5]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [7]:
c = b[1:3, 3:5]

In [8]:
c

array([[ 9, 10],
       [14, 15]])

In [9]:
c.shape

(2, 2)