# Fancy Indexing

**sirasi onemli olmadan bir list olusturuyorum ve indis olarak x'in icinde bir list olarak yani, koseli parantez icinde fancy index kullaniyorum istersem bu indisi buyukten kucuge sayilarla olustururum yani bu listin sirasi onemli degil**

**ayni mantigi matrixlerde de kullanabilirim**

**bir onceki slice yapma mantiginda eger iki tarafi da slice verirsem sayi obegi degil bir matrix elde ederim**

**fancy indexing bu koseli parantezle yazdigim sey**

**istersem her iki tarafi da fancy index verebilirim**

**istersem bir matrixe tek bir indis verip istedigim satiri alabiliyordum, simdi birden fazla indisi fancy indexle verip istedidgim kadar satiri yine bir matrix olarak alabilirim**



In [3]:
import numpy as np

In [4]:
x = np.arange(1, 15)

In [5]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
type(x)

numpy.ndarray

In [7]:
indx = [4, 5, 7, 11]

In [8]:
x[indx]

array([ 5,  6,  8, 12])

# Fancy Indexing

In [9]:
b = np.arange(1, 41).reshape(8, 5)

In [10]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [11]:
c = b[0, [1, 3]] #fancy indexing bu koseli parantez icinde yazdigim sey

In [12]:
c

array([2, 4])

In [13]:
d = b[0:, [3, 4]] #boyle yaptigimda bir matrix donduruyorum

In [21]:
d

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25],
       [29, 30],
       [34, 35],
       [39, 40]])

In [19]:
d.shape

(8, 2)

In [14]:
m = b[[1, 4], [0,2]] #boyle yaptigim zaman yine row column mantiginda olmayan bir sayi obegi elde ediyorum
#burasi onemli, cizgiler cekmisim gibi dusun, cizgilerin kesisim noktalarindaki elemanlari aliyorum

In [15]:
m

array([ 6, 23])

In [28]:
m.shape

(2,)

In [30]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [31]:
b.shape

(8, 5)

In [35]:
indx1 = [0, 1, 4]

In [38]:
indx2 = [1,2]

In [46]:
ece = b[indx1][indx2] #satirlarin yine satirlarini alan bir yapi veriyor

In [41]:
ece

array([[ 6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25]])

In [42]:
efe = b[indx1]

In [43]:
efe.shape

(3, 5)

In [44]:
efe

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25]])

In [45]:
efe[indx2]

array([[ 6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25]])

* Fancy Indexing ile Istersem Degerleri Degistire de Bilirim, istersem hepsini ayni deger yaparim istersem her bir index icin farkli degerler yaparimm

In [47]:
x = np.arange(1, 21)

In [48]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [49]:
x[[1, 3, 8]] = 999

In [50]:
x

array([  1, 999,   3, 999,   5,   6,   7,   8, 999,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [54]:
x[[1, 3, 8]] = [9999, 9998, 99990]

In [55]:
x

array([    1,  9999,     3,  9998,     5,     6,     7,     8, 99990,
          10,    11,    12,    13,    14,    15,    16,    17,    18,
          19,    20])