# Subarray
**Bir arrayden bir parcayi oldugu gibi baska bir degiskene atayip onda degisiklikler yaparsam asil matrixim tum bu degisikliklerden etkileniyor**


In [1]:
import numpy as np

In [2]:
a = np.arange(1, 21).reshape(4, 5)

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
b = a[:2, :3]

In [5]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [6]:
b.ndim

2

In [7]:
b[0, 0] = 100

In [8]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [11]:
d = a[:2, :3].copy() #degismemesi icin yapmam gereken sey copy methodunu kullanmak

In [10]:
d

array([[100,   2,   3],
       [  6,   7,   8]])