# Conditional Indexing

**Burda yaptigim sey de cok onemli, fancy index ile yarisir aslinda**

**Istersem iki numpy arrayinin ayni olan elemanlarini da kontrol edebilirim ama bunun icin uzunluklari ayni olmali**

**filter icinde and or ve not degil de &, | ve ~ kullanmaliyim**

**Her bir satiri tek tek incele**

In [4]:
import numpy as np

In [5]:
a = np.arange(1, 10)

In [6]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False])

In [8]:
a[a<5]

array([1, 2, 3, 4])

* filter tanimlayarak bir abstraction sagliyorum

In [9]:
filter = a < 6

In [10]:
a[filter]

array([1, 2, 3, 4, 5])

In [11]:
l1 = [1, 2, 3, 4]
l2= [1, 2, 3, 4]
# normal python listlerinde ayni durum soz konusu degil

In [12]:
l1 == l2

True

In [13]:
b = np.array([10, 2, 34, 5, 5, 6, 3, 2, 1])

In [14]:
c = a == b

In [17]:
c

array([False,  True, False, False,  True,  True, False, False, False])

In [18]:
type(c)

numpy.ndarray

In [15]:
a[a==b]

array([2, 5, 6])

In [16]:
filter1 = (a > 5) | (a>8)

In [19]:
a[filter1]

array([6, 7, 8, 9])

In [20]:
filter2 = (a > 5) & (a>8)

In [21]:
a[filter2]

array([9])

In [23]:
a = np.random.randint(30, size = (4,5))

In [24]:
a

array([[20, 25,  3, 12,  4],
       [ 5,  2,  5, 12, 28],
       [18, 20,  1,  7, 14],
       [14,  3, 11,  2, 23]])

In [25]:
filter3 = ~((a > 10) & (a < 20))

In [26]:
a[filter3]

array([20, 25,  3,  4,  5,  2,  5, 28, 20,  1,  7,  3,  2, 23])

In [27]:
a < 5

array([[False, False,  True, False,  True],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False,  True, False,  True, False]])

In [28]:
type(a)

numpy.ndarray

In [29]:
type(a < 7)

numpy.ndarray

In [32]:
filter3.shape

(4, 5)

In [6]:
n = np.array([1, 2, 3, None])

In [7]:
n

array([1, 2, 3, None], dtype=object)

In [8]:
n == None

array([False, False, False,  True])

In [9]:
n[n == None]

array([None], dtype=object)

In [10]:
n == 5

array([False, False, False, False])

In [19]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
e = np.random.randint(30, size = (4,5))

In [21]:
e

array([[10, 13, 23, 20, 17],
       [ 9, 17, 25, 21,  6],
       [ 5,  4,  6, 22, 10],
       [29, 10, 19, 24,  4]])

In [24]:
filter5 = e % 5 == 0

In [25]:
e[~filter5]

array([13, 23, 17,  9, 17, 21,  6,  4,  6, 22, 29, 19, 24,  4])

In [26]:
filter5

array([[ True, False, False,  True, False],
       [False, False,  True, False, False],
       [ True, False, False, False,  True],
       [False,  True, False, False, False]])