**sum methodu belli axislerdeki veya array icindeki tum elemanlari toplamami saglayacak**

**sum icine ndarray atarsam tum elemanlarini topluyor, eger sum icine filter atarsam o filteri saglayan kac durum oldugunu sayiyor**

**yazdigim kosul bana True ve False'lardan olusan bir yapi dondurecek**

In [1]:
import numpy as np

In [2]:
names = np.array(["ece", "ece", "melis"])

In [3]:
filter = names == "ece"

In [4]:
np.sum(filter)

2

In [5]:
filter


array([ True,  True, False])

In [7]:
names[filter]

array(['ece', 'ece'], dtype='<U5')

In [9]:
np.sum(names[filter]) #string uzerinde toplama yapamiyorum

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U5'), dtype('<U5')) -> None

# Belirli Axis Uzerinde Toplama


In [10]:
a = np.arange(1, 21).reshape(4, 5)

In [11]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [12]:
np.sum(a, axis = 0)

array([34, 38, 42, 46, 50])

In [13]:
np.sum(a, axis = 1)

array([15, 40, 65, 90])