**Tum elemanlar verilen sarti sagliyor mu saglamiyor mu bunu kontrol etmek icin kullaniyorum, yani bir sarti kontrol ediyorum**

In [2]:
import numpy as np

In [3]:
a = np.arange(1, 21).reshape(4, 5)

In [4]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [5]:
a > -1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [6]:
np.all(a > -1)

True

In [7]:
filter = a > -1

In [8]:
np.all(filter)

True

In [9]:
np.all(a > -1, axis = 1)

array([ True,  True,  True,  True])

In [10]:
filter2 = a > 5

In [11]:
np.all(filter2)

False

In [13]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [12]:
np.all(filter2, axis = 1)

array([False,  True,  True,  True])

In [14]:
np.all(filter2, axis = 0)

array([False, False, False, False, False])