**Herhangi bir eleman verilen sarti sagliyor mu diye kontrol ediyorum, all durumunda hepsi mi ayni diye kontrol ediyordum**

In [2]:
import numpy as np

In [7]:
a = np.arange(20).reshape(4,5)

In [8]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
a > 17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True]])

In [10]:
np.any(a > 17)

True

In [11]:
np.any(a > 17, axis = 1)

array([False, False, False,  True])