In [1]:
import numpy as np

In [17]:
a = np.linspace(3, 21, 5, dtype = int)

In [18]:
b = np.linspace(4, 22, 5, dtype = int)

In [19]:
a

array([ 3,  7, 12, 16, 21])

In [20]:
b

array([ 4,  8, 13, 17, 22])

In [21]:
a.shape

(5,)

In [22]:
b.shape

(5,)

In [23]:
c = np.stack([a, b], axis = 1)

In [24]:
c

array([[ 3,  4],
       [ 7,  8],
       [12, 13],
       [16, 17],
       [21, 22]])

In [25]:
c.shape

(5, 2)

In [26]:
d = np.stack([a, b], axis = 0)

In [27]:
d

array([[ 3,  7, 12, 16, 21],
       [ 4,  8, 13, 17, 22]])

In [28]:
d.shape

(2, 5)