# Indexing

In [1]:
import numpy as np

In [3]:
a = np.arange(1,21).reshape(4,5)

In [4]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [5]:
a[0]

array([1, 2, 3, 4, 5])

In [6]:
a[1, 1] = 333.90

In [7]:
a

array([[  1,   2,   3,   4,   5],
       [  6, 333,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [15]:
b = np.arange(1, 201).reshape(20, 10)

In [16]:
b

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170

# Slicing

In [21]:
b[3:15:2, 4:7:5]

array([[ 35],
       [ 55],
       [ 75],
       [ 95],
       [115],
       [135]])

In [23]:
b[:,3].shape

(20,)

In [26]:
b[::3, 4].shape

(7,)

In [25]:
b[:5, :5]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]])

In [27]:
b[:5, :5].shape

(5, 5)

# Fancy Indexing

In [28]:
indx = [1, 3, 5]

In [29]:
b[0, indx]

array([2, 4, 6])

In [30]:
b[0, indx].ndim

1

In [31]:
b[0, indx].shape

(3,)

In [32]:
b[:, indx]

array([[  2,   4,   6],
       [ 12,  14,  16],
       [ 22,  24,  26],
       [ 32,  34,  36],
       [ 42,  44,  46],
       [ 52,  54,  56],
       [ 62,  64,  66],
       [ 72,  74,  76],
       [ 82,  84,  86],
       [ 92,  94,  96],
       [102, 104, 106],
       [112, 114, 116],
       [122, 124, 126],
       [132, 134, 136],
       [142, 144, 146],
       [152, 154, 156],
       [162, 164, 166],
       [172, 174, 176],
       [182, 184, 186],
       [192, 194, 196]])

In [33]:
b[:, indx].shape

(20, 3)

In [34]:
b[indx]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [35]:
b[0:11, indx]

array([[  2,   4,   6],
       [ 12,  14,  16],
       [ 22,  24,  26],
       [ 32,  34,  36],
       [ 42,  44,  46],
       [ 52,  54,  56],
       [ 62,  64,  66],
       [ 72,  74,  76],
       [ 82,  84,  86],
       [ 92,  94,  96],
       [102, 104, 106]])

In [36]:
b[0:11, indx].shape

(11, 3)

In [37]:
b[indx, 0:5]

array([[11, 12, 13, 14, 15],
       [31, 32, 33, 34, 35],
       [51, 52, 53, 54, 55]])

In [38]:
b[indx, 0:5].shape

(3, 5)

In [39]:
c = np.arange(1, 21)

In [40]:
c[[0, 5, 10]] = 20

In [41]:
c

array([20,  2,  3,  4,  5, 20,  7,  8,  9, 10, 20, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [42]:
c[[2, 6]] = [99999, 99999]

In [43]:
c

array([   20,     2, 99999,     4,     5,    20, 99999,     8,     9,
          10,    20,    12,    13,    14,    15,    16,    17,    18,
          19,    20])

In [44]:
d = np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a=np.arange(1,13).reshape(3,4) 

In [46]:
b=a[1,(1,3)] 

In [47]:
b.shape

(2,)

# Subarray

In [50]:
f = np.arange(1, 21).reshape(4, 5)


In [51]:
f

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [52]:
d = f[0:3, 0:3]

In [53]:
d

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [54]:
d[0,0] = 1000

In [55]:
d

array([[1000,    2,    3],
       [   6,    7,    8],
       [  11,   12,   13]])

In [56]:
f

array([[1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15],
       [  16,   17,   18,   19,   20]])

In [57]:
g = d = f[0:3, 0:3].copy()

In [58]:
g

array([[1000,    2,    3],
       [   6,    7,    8],
       [  11,   12,   13]])

In [59]:
g[0,1] = 999
g

array([[1000,  999,    3],
       [   6,    7,    8],
       [  11,   12,   13]])

In [60]:
f

array([[1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15],
       [  16,   17,   18,   19,   20]])