In [2]:
import numpy as np

# Concatenation

In [11]:
a = np.array([1, 2, 3, 4])

In [12]:
a

array([1, 2, 3, 4])

In [15]:
a.shape

(4,)

In [13]:
b = np.array([5, 6, 7, 8, 9])

In [14]:
b

array([5, 6, 7, 8, 9])

In [7]:
c = np.concatenate([a, b])

In [8]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
c.shape

(9,)

In [17]:
list1 = [10, 20, 30, 40]

In [18]:
list2 = [60, 70]

In [19]:
list1 + list2

[10, 20, 30, 40, 60, 70]

In [12]:
list1 * 3

[10, 20, 30, 40, 10, 20, 30, 40, 10, 20, 30, 40]

In [24]:
d = np.concatenate([a, b], axis = 0)

In [26]:
type(d)

numpy.ndarray

In [15]:
list3 = [1, 2.1, "5.4"]

In [16]:
np.concatenate([a, list3])

array(['1', '2', '3', '4', '1', '2.1', '5.4'], dtype='<U32')

In [17]:
matrix1 = np.arange(1, 31).reshape(5, 6)

In [29]:
matrix2 = np.arange(21, 51).reshape(5, 6)

In [18]:
matrix1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [30]:
matrix2

array([[21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50]])

In [33]:
matrix3 = np.concatenate([matrix1, matrix2], axis=1)

In [34]:
matrix3

array([[ 1,  2,  3,  4,  5,  6, 21, 22, 23, 24, 25, 26],
       [ 7,  8,  9, 10, 11, 12, 27, 28, 29, 30, 31, 32],
       [13, 14, 15, 16, 17, 18, 33, 34, 35, 36, 37, 38],
       [19, 20, 21, 22, 23, 24, 39, 40, 41, 42, 43, 44],
       [25, 26, 27, 28, 29, 30, 45, 46, 47, 48, 49, 50]])

# Stack

* Stack mantiginda olay yeni bir dimension ekleyip onun uzerinden bir ekleme yapmak

In [48]:
a = np.array([10, 11, 12, 13])

In [49]:
b = np.array([15, 16, 17, 18])

In [50]:
c = np.concatenate([a, b])

In [51]:
c

array([10, 11, 12, 13, 15, 16, 17, 18])

In [59]:
np.stack([a, b])

array([[10, 11, 12, 13],
       [15, 16, 17, 18]])

In [58]:
np.stack([matrix1, matrix2])

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]],

       [[21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38],
        [39, 40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49, 50]]])