# Conditional Indexing (Filtering)

In [1]:
import numpy as np

In [12]:
a = np.random.randint(20, size=(10,))

In [13]:
a

array([17, 15, 16, 14,  6, 16, 15, 18,  5,  9])

In [15]:
a < 4

array([False, False, False, False, False, False, False, False, False,
       False])

In [18]:
filter = a > 10

In [19]:
a[filter]

array([17, 15, 16, 14, 16, 15, 18])

In [23]:
b = np.random.randint(20, size=(10, ))

In [24]:
b

array([14,  2,  3,  6, 19,  5, 18, 13, 13,  9])

In [25]:
a == b

array([False, False, False, False, False, False, False, False, False,
        True])

In [26]:
filter = a == b

In [27]:
a[filter]

array([9])

In [28]:
a[a==b]

array([9])

In [29]:
b[a==b]

array([9])

In [30]:
a[(a < 5) | (a > 10)]

array([17, 15, 16, 14, 16, 15, 18])

In [31]:
b[(b < 5) | (b > 10)]

array([14,  2,  3, 19, 18, 13, 13])

In [32]:
b[(b < 5) | (b > 10)].shape

(7,)

In [33]:
a[a % 5 == 0]

array([15, 15,  5])

In [34]:
a[(a % 5 == 0) & (a > 5)]

array([15, 15])

# Filtreleme Yaparken Degilini Almak

In [35]:
m = np.random.randint(30, size = (4, 5))

In [36]:
m

array([[13, 18, 15,  4,  0],
       [22,  3,  3, 24, 28],
       [26, 10,  8, 11, 12],
       [12, 17,  2,  2, 28]])

In [41]:
m < 5

array([[False, False, False,  True,  True],
       [False,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False,  True,  True, False]])

In [37]:
m[m<5]

array([4, 0, 3, 3, 2, 2])

In [38]:
m[m<5].shape

(6,)

In [39]:
m[~((m>5) & (m < 20))]

array([ 4,  0, 22,  3,  3, 24, 28, 26,  2,  2, 28])

In [48]:
my_array = np.array([3, 5, 7, 7, 10, 7, None])

In [49]:
my_array.dtype

dtype('O')

In [50]:
my_array

array([3, 5, 7, 7, 10, 7, None], dtype=object)

In [51]:
my_array == None

array([False, False, False, False, False, False,  True])

In [53]:
my_array[my_array == 7]

array([7, 7, 7], dtype=object)