# All and Any

In [1]:
import numpy as np

In [3]:
a = np.arange(1, 21).reshape(4, 5)

In [4]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [6]:
np.all(a > -1)

In [8]:
np.all(a > 5)

False

In [9]:
np.all(a == 5)

False

In [12]:
b = np.full((5, 5), 7)

In [13]:
b

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [14]:
np.all(b == 7)

True

In [15]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [16]:
np.all(a>5)

False

In [17]:
a > 5

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [18]:
np.all(a>5, axis = 0)

array([False, False, False, False, False])

In [20]:
array = np.all(a>5, axis = 1)

In [21]:
array

array([False,  True,  True,  True])

In [22]:
array.shape

(4,)