# listlerden array yaratmak


In [4]:
import numpy as np

list'ten bir numpy array yaratmis oldum

In [9]:
x = np.array(("ece", "ege"))
x

array(['ece', 'ege'], dtype='<U3')

In [5]:
y = np.array((1, 2, 3, 4, 5))

In [6]:
type(y)

numpy.ndarray

In [10]:
z = np.array([1, 2, 3, 4, "a"])
z

array(['1', '2', '3', '4', 'a'], dtype='<U11')

# Array'e tipini manuel olarak vermek

In [11]:
u = np.array([1, 3, 6.7, 5, 67])
u

array([ 1. ,  3. ,  6.7,  5. , 67. ])

In [12]:
u = np.array([1, 3, 6.7, 5, 67], dtype = "int32")
u

array([ 1,  3,  6,  5, 67])

In [13]:
u = np.array([1, 3, 6.7, 5, 67], dtype = "str")
u

array(['1', '3', '6.7', '5', '67'], dtype='<U3')

# zero matrix

In [14]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
zeros = np.zeros(10, dtype=bool)
zeros

array([False, False, False, False, False, False, False, False, False,
       False])

In [18]:
zeros = np.zeros(5, dtype = str)
zeros

array(['', '', '', '', ''], dtype='<U1')

In [19]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.zeros([3, 5, 6])

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

# Belli bir degerle doldurmak

In [21]:
z = np.full((4, 4), 5)

In [22]:
z

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [23]:
np.full((4, 5), 5.67)

array([[5.67, 5.67, 5.67, 5.67, 5.67],
       [5.67, 5.67, 5.67, 5.67, 5.67],
       [5.67, 5.67, 5.67, 5.67, 5.67],
       [5.67, 5.67, 5.67, 5.67, 5.67]])

In [24]:
np.full((4, 5), 5.67, dtype = str)

array([['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5']], dtype='<U1')

In [36]:
np.full((4, 5), 5.67, str)

array([['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5']], dtype='<U1')

In [25]:
np.full((4, 5), "5.67")

array([['5.67', '5.67', '5.67', '5.67', '5.67'],
       ['5.67', '5.67', '5.67', '5.67', '5.67'],
       ['5.67', '5.67', '5.67', '5.67', '5.67'],
       ['5.67', '5.67', '5.67', '5.67', '5.67']], dtype='<U4')

# Ardisik sayilardan array olusturmak

In [26]:
np.arange(0, 12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
np.arange(2, 12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
np.arange(2.5, 12, 2)

array([ 2.5,  4.5,  6.5,  8.5, 10.5])

In [32]:
np.arange(2, 12, -2)

array([], dtype=float64)

In [30]:
np.arange(12, 2, -2)

array([12, 10,  8,  6,  4])

# Bir araliktan birbirine esit mesafede noktalar olusturmak

In [35]:
np.linspace(1, 2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [37]:
np.linspace(1.5, 4.7, num = 10, endpoint = False)

array([1.5 , 1.82, 2.14, 2.46, 2.78, 3.1 , 3.42, 3.74, 4.06, 4.38])

In [38]:
np.linspace(1, 30, 100)

array([ 1.        ,  1.29292929,  1.58585859,  1.87878788,  2.17171717,
        2.46464646,  2.75757576,  3.05050505,  3.34343434,  3.63636364,
        3.92929293,  4.22222222,  4.51515152,  4.80808081,  5.1010101 ,
        5.39393939,  5.68686869,  5.97979798,  6.27272727,  6.56565657,
        6.85858586,  7.15151515,  7.44444444,  7.73737374,  8.03030303,
        8.32323232,  8.61616162,  8.90909091,  9.2020202 ,  9.49494949,
        9.78787879, 10.08080808, 10.37373737, 10.66666667, 10.95959596,
       11.25252525, 11.54545455, 11.83838384, 12.13131313, 12.42424242,
       12.71717172, 13.01010101, 13.3030303 , 13.5959596 , 13.88888889,
       14.18181818, 14.47474747, 14.76767677, 15.06060606, 15.35353535,
       15.64646465, 15.93939394, 16.23232323, 16.52525253, 16.81818182,
       17.11111111, 17.4040404 , 17.6969697 , 17.98989899, 18.28282828,
       18.57575758, 18.86868687, 19.16161616, 19.45454545, 19.74747475,
       20.04040404, 20.33333333, 20.62626263, 20.91919192, 21.21

# Normal Distribution ile Array Olusturmak

* (mean, std, array_size)

In [40]:
np.random.normal(0, 10, 5)

array([10.60445175,  2.44733072, -7.781474  ,  2.84184202, 19.02701249])

In [41]:
np.random.normal(10, 100, (4,5))

array([[  19.31456866,   34.04163886,  -80.01141524, -131.16194933,
        -197.13944533],
       [ -85.89812103,   35.45070528,  -25.88714694,  158.93733807,
         -88.34489389],
       [   8.41798211,   33.21743016,  115.44488667,   99.94319617,
         136.159359  ],
       [ 239.2248798 ,  -41.15027123,   71.78530699,   38.70085323,
          10.14651258]])

# Random Integer Degerler ile Array Uretmek

[low, high)

In [43]:
np.random.randint(3, 30, (3, 4))

array([[13,  8,  9, 29],
       [28, 14, 13,  8],
       [15, 10, 12,  3]])

In [45]:
np.random.randint(1, 5)

1

In [47]:
d = {}
for _ in range(2000):
    val = np.random.randint(1, 11)
    if val not in d:
        d[val] = 1
    else:
        d[val] += 1
        

In [48]:
d

{3: 187,
 4: 198,
 10: 193,
 5: 193,
 6: 196,
 1: 209,
 8: 210,
 9: 222,
 7: 184,
 2: 208}

In [54]:
for i in range(2, 20, 4):
    print(i)

2
6
10
14
18


# Identity Matrix

In [55]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# Array Islemleri

* python list'leri icin + ve * islemleri concatanete icin tanimli, elemanlari toplayamiyor ve carpamiyor

In [73]:
mya = [1, 2, 3, 4]
myb = [5, 6, 7, 8]

In [75]:
mya + myb

[1, 2, 3, 4, 5, 6, 7, 8]

In [77]:
mya * 3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [63]:
[1, 2, 3, 4] + [5, 6, 7, 8]

[1, 2, 3, 4, 5, 6, 7, 8]

In [67]:
[5, 6, 7, 8] * 3

[5, 6, 7, 8, 5, 6, 7, 8, 5, 6, 7, 8]

In [68]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([11, 22, 33, 44, 55])

In [69]:
x + y

array([12, 24, 36, 48, 60])

In [70]:
x * y

array([ 11,  44,  99, 176, 275])

In [78]:
x = x * 3
x

array([ 3,  6,  9, 12, 15])

# Reshape 

In [8]:
ece = np.arange(1, 31)

In [9]:
ece

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [12]:
ece.reshape((5, 6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [13]:
ece.reshape((5, 6)).ndim

2

# -1 ile Boyuta Karar Vermek

In [14]:
ece.reshape(3, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [15]:
ece.reshape(-1,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

# Yeni Bir Boyut Eklemek

In [20]:
ece1 = np.arange(1,21).reshape(4,5)

In [21]:
ece1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [25]:
ece1[:, np.newaxis]

array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20]]])

In [26]:
A = np.array([[3],
             [11],
             [4],
             [5]])

In [29]:
A.shape

(4, 1)

In [35]:
B = np.array([5, 0, 3]).reshape(1,3)

In [36]:
B.shape

(1, 3)

In [37]:
C = A - B

In [38]:
C

array([[-2,  3,  0],
       [ 6, 11,  8],
       [-1,  4,  1],
       [ 0,  5,  2]])