# NEDEN NumPy?

In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [10]:
a = np.array([1.23, 2, 3, 4], dtype = int)
a

array([1, 2, 3, 4])

In [7]:
type(a)

numpy.ndarray

#sifirdan array olusturma 

In [11]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3, 5), dtype = "float32")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [15]:
np.ones(20, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
np.full(10, 4)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [17]:
np.full((3, 4), 9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [18]:
np.arange(0, 31, 3)


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [19]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [20]:
np.random.normal(10, 4, (3, 4))

array([[11.88354993,  6.88571512,  4.58066609, 12.33312388],
       [ 7.14265438, 14.2445399 ,  9.03513946, 12.06889853],
       [ 2.65419731,  4.68915447,  5.63774701,  6.81465413]])

In [26]:
np.random.randint(0, 10, (3, 4))

array([[5, 9, 5, 0],
       [1, 2, 1, 1],
       [8, 0, 1, 3]])

In [27]:
np.random.randint(0, 20, size = (3, 4))

array([[12, 10, 19,  5],
       [ 4,  4,  1, 18],
       [ 3, 19, 19,  2]])

In [29]:
np.random.randint(10, 20, size = (10))

array([16, 16, 14, 11, 15, 15, 15, 12, 19, 14])