# reshape

In [1]:
import numpy as np


In [4]:
a = np.arange(1, 10)

In [5]:
a.size

9

In [6]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**OR**

In [9]:
np.arange(10, 30).size

20

In [10]:
np.arange(10, 30).reshape((4, 5))

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [16]:
np.arange(1, 10).reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])