# split

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])

In [3]:
np.split(x, [3, 5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [5]:
y = np.arange(8.0)
y


array([0., 1., 2., 3., 4., 5., 6., 7.])

In [15]:
np.split(y, [3, 5, 6, 20])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

In [12]:
a, b, c = np.split(x, [3, 5])

In [8]:
a

array([1, 2, 3])

In [9]:
b

array([99, 99])

In [10]:
c

array([3, 2, 1])

# iki boyutlu ayirma

In [16]:
matrix = np.arange(16).reshape(4,4)

In [18]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
np.vsplit(matrix, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [20]:
ust, alt = np.vsplit(matrix, [2])

In [21]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
np.hsplit(matrix, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [24]:
sag, sol = np.hsplit(matrix, [2])

In [25]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [26]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])